name: PR Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Check PR title follows conventional commits
  pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  # Check for changed files
  changed-files:
    name: Detect Changed Files
    runs-on: ubuntu-latest

    outputs:
      src: ${{ steps.changes.outputs.src }}
      tests: ${{ steps.changes.outputs.tests }}
      docs: ${{ steps.changes.outputs.docs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
              - 'public/**'
              - '*.config.*'
            tests:
              - 'e2e/**'
              - 'tests/**'
            docs:
              - '**.md'
              - 'docs/**'

  # Run tests only if source code changed
  conditional-tests:
    name: Conditional Tests
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.src == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run quick tests
        run: |
          npm run lint
          npm run type-check

  # Add size comparison comment
  size-report:
    name: Bundle Size Report
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.src == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get bundle size
        id: bundle-size
        run: |
          SIZE=$(du -sh dist | cut -f1)
          echo "size=$SIZE" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const size = '${{ steps.bundle-size.outputs.size }}';
            const comment = `### 📦 Bundle Size Report\n\nTotal build size: **${size}**`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
